apply plugin: "java"

version = '1.0'
sourceSets.main.java.srcDirs = ["src"]

repositories {
    mavenCentral()

    ivy {
        url = 'https://github.com/'
        patternLayout { artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar' }
        metadataSources { artifact() }
    }

    ivy {
        url = 'https://github.com/'
        patternLayout { artifact '/[organisation]/[module]/releases/[revision]/download/dependencies.jar' }
        metadataSources { artifact() }
    }

    ivy {
        url = 'https://github.com/'
        patternLayout { artifact '/[organisation]/[module]/releases/download/master/[revision].jar' }
        metadataSources { artifact() }
    }

    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://maven.aliyun.com/repository/central' }
    maven { url 'https://maven.fastmirror.net/repository/spongepowered/' }
    maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
}

java {
    targetCompatibility = JavaVersion.VERSION_17
    sourceCompatibility = JavaVersion.VERSION_17
}

ext {
    mindustryVersion = "v160.5"
    isWindows = System.getProperty("os.name").toLowerCase().contains("windows")
    sdkRoot = System.getenv("ANDROID_HOME") ?: System.getenv("ANDROID_SDK_ROOT")
}

dependencies {
    compileOnly mindustryVersion == "be" ? "Anuken:MindustryBuilds:latest" : "Anuken:Mindustry:$mindustryVersion"
    annotationProcessor mindustryVersion == "be" ? "Anuken:MindustryBuilds:latest" : "Anuken:Mindustry:$mindustryVersion"
}

jar {
    archiveFileName = "${project.name}Desktop.jar"

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    from(projectDir) {
        include "mod.hjson"
    }

    from("assets/") {
        include "**"
    }
}

tasks.register('jarAndroid') {
    dependsOn "jar"
    def projectName = project.name

    doLast {
        if (!sdkRoot || !new File(sdkRoot).exists()) throw new GradleException("No valid Android SDK found. Ensure that ANDROID_HOME is set to your Android SDK directory.")

        def platformRoot = new File("$sdkRoot/platforms/").listFiles().sort().reverse().find { f -> new File(f, "android.jar").exists() }

        if (!platformRoot) throw new GradleException("No android.jar found. Ensure that you have an Android platform installed.")

        def dependencies = (configurations.compileClasspath.asList() + configurations.runtimeClasspath.asList() + [new File(platformRoot, "android.jar")]).collect { "--classpath $it.path" }.join(" ")

        def d8 = isWindows ? "E:/Tools/android-sdk-windows/build-tools/37.0.0/d8.bat" : "d8"

        "$d8 -JXmx4g -JXss2m $dependencies --min-api 14 --output ${projectName}Android.jar ${projectName}Desktop.jar"
                .execute(null, new File("build/libs"))
                .waitForProcessOutput(System.out, System.err)
    }
}

tasks.register('deploy', Jar) {
    def projectName = project.name
    dependsOn "jarAndroid"
    dependsOn "jar"
    archiveFileName = "${projectName}.jar"

    from { [zipTree("build/libs/${projectName}Desktop.jar"), zipTree("build/libs/${projectName}Android.jar")] }

    doLast {
        delete {
            delete "build/libs/${projectName}Android.jar"
        }
    }
}

tasks.register('runOnClient') {
    dependsOn "deploy"
    doLast {
        delete {
            delete "C:/Users/user/AppData/Roaming/Mindustry/mods/${project.archivesBaseName}.jar"
            delete "C:/Users/user/AppData/Roaming/Mindustry/mods/${project.archivesBaseName}.zip"
        }
        copy {
            from "$buildDir/libs"
            into "C:/Users/user/AppData/Roaming/Mindustry/mods"
            include "${project.archivesBaseName}.jar"
        }
        exec {
            commandLine 'java', '-jar', '"C:/Users/user/Desktop/MindustryX-2026.05.X35-Desktop.jar"'
        }
    }
}